<?php

use App\Http\Controllers\Inmopro\AccountsReceivableController;
use App\Http\Controllers\Inmopro\AdvisorAgendaEventController;
use App\Http\Controllers\Inmopro\AdvisorController;
use App\Http\Controllers\Inmopro\AdvisorLevelController;
use App\Http\Controllers\Inmopro\AdvisorMembershipController;
use App\Http\Controllers\Inmopro\AdvisorReminderController;
use App\Http\Controllers\Inmopro\AgendaController;
use App\Http\Controllers\Inmopro\AppBrandingController;
use App\Http\Controllers\Inmopro\AttentionTicketController;
use App\Http\Controllers\Inmopro\CashAccountController;
use App\Http\Controllers\Inmopro\CityController;
use App\Http\Controllers\Inmopro\ClientController;
use App\Http\Controllers\Inmopro\ClientTypeController;
use App\Http\Controllers\Inmopro\CommissionController;
use App\Http\Controllers\Inmopro\CommissionStatusController;
use App\Http\Controllers\Inmopro\DashboardController;
use App\Http\Controllers\Inmopro\DateroController;
use App\Http\Controllers\Inmopro\FinancialController;
use App\Http\Controllers\Inmopro\LotAiFollowUpSuggestionController;
use App\Http\Controllers\Inmopro\LotController;
use App\Http\Controllers\Inmopro\LotPreReservationController;
use App\Http\Controllers\Inmopro\LotStatusController;
use App\Http\Controllers\Inmopro\LotTransferConfirmationController;
use App\Http\Controllers\Inmopro\MembershipTypeController;
use App\Http\Controllers\Inmopro\ProcessDiagramsController;
use App\Http\Controllers\Inmopro\ProjectController;
use App\Http\Controllers\Inmopro\ReportController;
use App\Http\Controllers\Inmopro\ReportSalesConfigController;
use App\Http\Controllers\Inmopro\TeamController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified'])->prefix('inmopro')->name('inmopro.')->group(function (): void {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::get('projects/excel-template', [ProjectController::class, 'excelTemplate'])->name('projects.excel-template');
    Route::post('projects/import-from-excel', [ProjectController::class, 'importFromExcel'])->name('projects.import-from-excel');
    Route::resource('projects', ProjectController::class);
    Route::get('lots/export-pdf', [LotController::class, 'exportPdf'])->name('lots.export-pdf');
    Route::post('lots/{lot}/ai-follow-up-suggestion', LotAiFollowUpSuggestionController::class)
        ->middleware('throttle:ai')
        ->name('lots.ai-follow-up-suggestion');
    Route::resource('lots', LotController::class);
    Route::get('clients/search', [ClientController::class, 'search'])->name('clients.search');
    Route::get('clients/export-excel', [ClientController::class, 'exportExcel'])->name('clients.export-excel');
    Route::post('clients/import-from-excel', [ClientController::class, 'importFromExcel'])->name('clients.import-from-excel');
    Route::resource('clients', ClientController::class);
    Route::resource('client-types', ClientTypeController::class)->parameters(['client-types' => 'client_type']);
    Route::resource('cities', CityController::class);
    Route::get('advisors/search', [AdvisorController::class, 'search'])->name('advisors.search');
    Route::put('advisors/{advisor}/cazador-access', [AdvisorController::class, 'updateCazadorAccess'])->name('advisors.cazador-access.update');
    Route::resource('advisors', AdvisorController::class)->except(['destroy']);
    Route::resource('dateros', DateroController::class);
    Route::resource('teams', TeamController::class);
    Route::get('membership-types/{membership_type}/bulk-assign', [MembershipTypeController::class, 'bulkAssign'])->name('membership-types.bulk-assign');
    Route::post('membership-types/{membership_type}/bulk-assign', [MembershipTypeController::class, 'bulkAssignStore'])->name('membership-types.bulk-assign.store');
    Route::resource('membership-types', MembershipTypeController::class)->parameters(['membership-types' => 'membership_type']);
    Route::post('advisor-memberships/{advisor_membership}/payments', [AdvisorMembershipController::class, 'storePayment'])->name('advisor-memberships.payments.store');
    Route::resource('advisor-memberships', AdvisorMembershipController::class)->parameters(['advisor-memberships' => 'advisor_membership']);
    Route::resource('lot-statuses', LotStatusController::class)->parameters(['lot-statuses' => 'lot_status']);
    Route::resource('commission-statuses', CommissionStatusController::class)->parameters(['commission-statuses' => 'commission_status']);
    Route::resource('advisor-levels', AdvisorLevelController::class)->parameters(['advisor-levels' => 'advisor_level']);
    Route::get('financial', [FinancialController::class, 'index'])->name('financial.index');
    Route::get('accounts-receivable', [AccountsReceivableController::class, 'index'])->name('accounts-receivable.index');
    Route::post('lots/{lot}/installments', [AccountsReceivableController::class, 'storeInstallment'])->name('lots.installments.store');
    Route::post('lots/{lot}/payments', [AccountsReceivableController::class, 'storePayment'])->name('lots.payments.store');
    Route::get('cash-accounts', [CashAccountController::class, 'index'])->name('cash-accounts.index');
    Route::post('cash-accounts', [CashAccountController::class, 'store'])->name('cash-accounts.store');
    Route::post('cash-accounts/{cash_account}/entries', [CashAccountController::class, 'storeEntry'])->name('cash-accounts.entries.store');
    Route::get('commissions', [CommissionController::class, 'index'])->name('commissions.index');
    Route::post('commissions/{commission}/mark-as-paid', [CommissionController::class, 'markAsPaid'])->name('commissions.mark-as-paid');
    Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('reports/pdf', [ReportController::class, 'pdf'])->name('reports.pdf');
    Route::get('reports/csv', [ReportController::class, 'csv'])->name('reports.csv');
    Route::get('report-settings', [ReportSalesConfigController::class, 'edit'])->name('report-settings.edit');
    Route::put('report-settings', [ReportSalesConfigController::class, 'update'])->name('report-settings.update');
    Route::get('branding', [AppBrandingController::class, 'edit'])->name('branding.edit');
    Route::put('branding', [AppBrandingController::class, 'update'])->name('branding.update');
    Route::get('attention-tickets/calendar', [AttentionTicketController::class, 'calendar'])->name('attention-tickets.calendar');
    Route::get('attention-tickets/{attention_ticket}/delivery-deed', [AttentionTicketController::class, 'deliveryDeed'])->name('attention-tickets.delivery-deed');
    Route::post('attention-tickets/{attention_ticket}/delivery-deed/mark-signed', [AttentionTicketController::class, 'markDeedSigned'])->name('attention-tickets.delivery-deed.mark-signed');
    Route::resource('attention-tickets', AttentionTicketController::class)->parameters(['attention-tickets' => 'attention_ticket']);
    Route::get('lot-pre-reservations', [LotPreReservationController::class, 'index'])->name('lot-pre-reservations.index');
    Route::post('lot-pre-reservations', [LotPreReservationController::class, 'store'])->name('lot-pre-reservations.store');
    Route::post('lot-pre-reservations/{lot_pre_reservation}/approve', [LotPreReservationController::class, 'approve'])->name('lot-pre-reservations.approve');
    Route::post('lot-pre-reservations/{lot_pre_reservation}/reject', [LotPreReservationController::class, 'reject'])->name('lot-pre-reservations.reject');
    Route::get('lot-transfer-confirmations', [LotTransferConfirmationController::class, 'index'])->name('lot-transfer-confirmations.index');
    Route::get('lots/{lot}/transfer-confirmation', [LotTransferConfirmationController::class, 'create'])->name('lots.transfer-confirmation');
    Route::post('lots/{lot}/transfer-confirmation', [LotTransferConfirmationController::class, 'store'])->name('lots.transfer-confirmation.store');
    Route::post('lot-transfer-confirmations/{lot_transfer_confirmation}/approve', [LotTransferConfirmationController::class, 'approve'])->name('lot-transfer-confirmations.approve');
    Route::post('lot-transfer-confirmations/{lot_transfer_confirmation}/reject', [LotTransferConfirmationController::class, 'reject'])->name('lot-transfer-confirmations.reject');
    Route::get('process-diagrams', ProcessDiagramsController::class)->name('process-diagrams.index');
    Route::get('agenda', [AgendaController::class, 'index'])->name('agenda.index');
    Route::post('advisor-agenda-events', [AdvisorAgendaEventController::class, 'store'])->name('advisor-agenda-events.store');
    Route::put('advisor-agenda-events/{advisor_agenda_event}', [AdvisorAgendaEventController::class, 'update'])->name('advisor-agenda-events.update');
    Route::delete('advisor-agenda-events/{advisor_agenda_event}', [AdvisorAgendaEventController::class, 'destroy'])->name('advisor-agenda-events.destroy');
    Route::post('advisor-reminders', [AdvisorReminderController::class, 'store'])->name('advisor-reminders.store');
    Route::put('advisor-reminders/{advisor_reminder}', [AdvisorReminderController::class, 'update'])->name('advisor-reminders.update');
    Route::delete('advisor-reminders/{advisor_reminder}', [AdvisorReminderController::class, 'destroy'])->name('advisor-reminders.destroy');
    Route::post('advisor-reminders/{advisor_reminder}/complete', [AdvisorReminderController::class, 'complete'])->name('advisor-reminders.complete');
});
