<?php

use App\Http\Controllers\Inmopro\AccountsReceivableController;
use App\Http\Controllers\Inmopro\AdvisorController;
use App\Http\Controllers\Inmopro\AdvisorLevelController;
use App\Http\Controllers\Inmopro\AdvisorMembershipController;
use App\Http\Controllers\Inmopro\AttentionTicketController;
use App\Http\Controllers\Inmopro\CashAccountController;
use App\Http\Controllers\Inmopro\CityController;
use App\Http\Controllers\Inmopro\ClientController;
use App\Http\Controllers\Inmopro\ClientTypeController;
use App\Http\Controllers\Inmopro\CommissionController;
use App\Http\Controllers\Inmopro\CommissionStatusController;
use App\Http\Controllers\Inmopro\DashboardController;
use App\Http\Controllers\Inmopro\FinancialController;
use App\Http\Controllers\Inmopro\LotController;
use App\Http\Controllers\Inmopro\LotPreReservationController;
use App\Http\Controllers\Inmopro\LotStatusController;
use App\Http\Controllers\Inmopro\LotTransferConfirmationController;
use App\Http\Controllers\Inmopro\ProcessDiagramsController;
use App\Http\Controllers\Inmopro\ProjectController;
use App\Http\Controllers\Inmopro\ReportController;
use App\Http\Controllers\Inmopro\TeamController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified'])->prefix('inmopro')->name('inmopro.')->group(function (): void {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::get('projects/excel-template', [ProjectController::class, 'excelTemplate'])->name('projects.excel-template');
    Route::post('projects/import-from-excel', [ProjectController::class, 'importFromExcel'])->name('projects.import-from-excel');
    Route::resource('projects', ProjectController::class);
    Route::get('lots/export-pdf', [LotController::class, 'exportPdf'])->name('lots.export-pdf');
    Route::get('lot-transfer-confirmations', [LotTransferConfirmationController::class, 'index'])->name('lot-transfer-confirmations.index');
    Route::get('lots/{lot}/transfer-confirmation', [LotTransferConfirmationController::class, 'create'])->name('lots.transfer-confirmation.create');
    Route::post('lots/{lot}/transfer-confirmation', [LotTransferConfirmationController::class, 'store'])->name('lots.transfer-confirmation.store');
    Route::resource('lots', LotController::class);
    Route::get('clients/search', [ClientController::class, 'search'])->name('clients.search');
    Route::resource('clients', ClientController::class);
    Route::resource('client-types', ClientTypeController::class)->parameters(['client-types' => 'client_type']);
    Route::resource('cities', CityController::class);
    Route::get('advisors/search', [AdvisorController::class, 'search'])->name('advisors.search');
    Route::resource('advisors', AdvisorController::class)->except(['destroy']);
    Route::resource('teams', TeamController::class);
    Route::post('advisor-memberships/{advisor_membership}/payments', [AdvisorMembershipController::class, 'storePayment'])->name('advisor-memberships.payments.store');
    Route::resource('advisor-memberships', AdvisorMembershipController::class)->parameters(['advisor-memberships' => 'advisor_membership']);
    Route::resource('lot-statuses', LotStatusController::class)->parameters(['lot-statuses' => 'lot_status']);
    Route::resource('commission-statuses', CommissionStatusController::class)->parameters(['commission-statuses' => 'commission_status']);
    Route::resource('advisor-levels', AdvisorLevelController::class)->parameters(['advisor-levels' => 'advisor_level']);
    Route::get('financial', [FinancialController::class, 'index'])->name('financial.index');
    Route::get('accounts-receivable', [AccountsReceivableController::class, 'index'])->name('accounts-receivable.index');
    Route::post('lots/{lot}/installments', [AccountsReceivableController::class, 'storeInstallment'])->name('lots.installments.store');
    Route::post('lots/{lot}/payments', [AccountsReceivableController::class, 'storePayment'])->name('lots.payments.store');
    Route::get('cash-accounts', [CashAccountController::class, 'index'])->name('cash-accounts.index');
    Route::post('cash-accounts', [CashAccountController::class, 'store'])->name('cash-accounts.store');
    Route::post('cash-accounts/{cash_account}/entries', [CashAccountController::class, 'storeEntry'])->name('cash-accounts.entries.store');
    Route::get('commissions', [CommissionController::class, 'index'])->name('commissions.index');
    Route::post('commissions/{commission}/mark-as-paid', [CommissionController::class, 'markAsPaid'])->name('commissions.mark-as-paid');
    Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('reports/pdf', [ReportController::class, 'pdf'])->name('reports.pdf');
    Route::get('attention-tickets/calendar', [AttentionTicketController::class, 'calendar'])->name('attention-tickets.calendar');
    Route::get('attention-tickets/{attention_ticket}/delivery-deed', [AttentionTicketController::class, 'deliveryDeed'])->name('attention-tickets.delivery-deed');
    Route::post('attention-tickets/{attention_ticket}/delivery-deed/mark-signed', [AttentionTicketController::class, 'markDeedSigned'])->name('attention-tickets.delivery-deed.mark-signed');
    Route::resource('attention-tickets', AttentionTicketController::class)->parameters(['attention-tickets' => 'attention_ticket']);
    Route::get('lot-pre-reservations', [LotPreReservationController::class, 'index'])->name('lot-pre-reservations.index');
    Route::post('lot-pre-reservations/{lot_pre_reservation}/approve', [LotPreReservationController::class, 'approve'])->name('lot-pre-reservations.approve');
    Route::post('lot-pre-reservations/{lot_pre_reservation}/reject', [LotPreReservationController::class, 'reject'])->name('lot-pre-reservations.reject');
    Route::get('process-diagrams', ProcessDiagramsController::class)->name('process-diagrams.index');
});
